version: 2
jobs:
  build:
    docker:
      - image: crystallang/crystal
    environment:
      DOCS_PATH: "doc"
      GIT_USER: "icyleaf"
      GIT_EMAIL: "icyleaf.cn@gmail.com"
      GIT_REPO: "git@github.com:icyleaf/terminal-ui.cr.git"
      GH_REF: "github.com/icyleaf/terminal-ui.cr"
    branches:
      ignore:
        - gh-pages
    working_directory: ~/terminal-ui
    steps:
      - checkout
      - run:
          name: "Specs"
          command: crystal spec
